apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    owner: desynclabs.com
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  nginx.conf: |
    server {
      listen 3000;

      location / {
          root /usr/share/nginx/html;
          try_files $uri /index.html;
      }
    }