apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    owner: desynclabs.com
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
