apiVersion: v2
name       : splyce-frontend-app
description: Splyce frontend app Helm chart for Kubernetes
type       : application
version    : 0.0.1   # This is the Helm Chart version
appVersion : "latest" # This is the version of the application being deployed

keywords:
  - splyce-frontend-app
  - splyce

maintainers:
  - name : Pavlo Tsisar
    email: pavlo.tsisar@desynclabs.com
    url  : desynclabs.com